# Generated by Django 4.1.1 on 2023-02-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='common',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
