# Generated by Django 4.1.1 on 2023-02-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subscription_common'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='common',
        ),
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
